version: "3.3"

services:
  api:
    container_name: optimizer-api
    build: ./api
    env_file:
      - ./api/.env
    restart: always
    ports:
      - 5000:5000
    networks:
      - net

  web:
    container_name: optimizer-web
    build: ./web
    restart: always
    volumes:
      - ./web/app:/app
    environment:
      NODE_ENV: "development"
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - net

  # We set-up an NGINX to have a unique endpoint for app & api
  nginx:
    container_name: optimizer-nginx
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - api
      - web
    networks:
      - net

networks:
  net:
