name: ci
on:
  pull_request:
    branches:
      - master
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./app
          record: true
        env:
          CYPRESS_BASE_URL: https://rpo-git-dev-ansnoussi.vercel.app/
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
