name: jest
on:
  push:
    pull_request:
      - dev
jobs:
  utests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
        working-directory: ./app
      - name: Run tests
        continue-on-error: true
        working-directory: ./app
        run: yarn test --json --outputFile=jest-results.json
      - name: Process jest results with default
        if: always()
        uses: im-open/process-jest-test-results@v2.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-file: 'app/jest-results.json'