name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - dev
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
                working-directory: ./app
                with:
                   package-manager: yarn